{% set name = "flask-dramatiq" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6a5b2d6c8b1689021e3c868c15e260bc185c7da67f75c807d6a5d10b91882d08

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - click
    - dramatiq
    - flask

test:
  imports:
    - flask_dramatiq

about:
  home: https://pypi.org/project/flask-dramatiq/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Adds Dramatiq support to your Flask application'
  doc_url: https://flask-dramatiq.readthedocs.io/
  dev_url: https://gitlab.com/bersace/flask-dramatiq

extra:
  recipe-maintainers:
    - mcs07
